name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage coveralls  

      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x16 &
          export DISPLAY=:99

      - name: Run tests
        run: pytest tests.py
          
      - name: Run tests with coverage
        run: coverage run -m pytest tests.py
          
      - name: Generate coverage report
        run: coverage xml  
          
      - name: Submit coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }} 
        run: coveralls
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
        with:
          args: >
            -Dsonar.projectKey=stefastepanova_testing2
            -Dsonar.organization=stefastepanova
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml
