name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage coveralls

      - name: Run tests with coverage and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          xvfb-run -a coverage run -m unittest discover

      - name: Generate coverage report
        run: |
          coverage report -m

      - name: Upload to Coveralls
        run: |
          coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
        with:
          args: >
            -Dsonar.projectKey=stefastepanova_testing2
            -Dsonar.organization=stefastepanova
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml
